// --- OBFUSCATED WORD BANK ---
// Full vocabulary pool securely encrypted with custom XOR ciphers
// ABSOLUTELY NO spoilers in code comments!
export const PHRASE_POOL = [
    ["AQYQAQ==", "FAAWAQ=="],
    ["BBgXBRI=", "BAcdFA=="],
    ["EB0XAQg=", "HwAHFwM="],
    ["EQYAAQ==", "EQML"],
    ["HwAcAR8=", "FAAfBg=="],
    ["Ex0TAwkb", "EQML"],
    ["FRoGEAMH", "EQML"],
    ["AA4GARQ=", "GgoeCwg="],
    ["BBoc", "EQMdEwMH"],
    ["BBsTFg==", "EQYBDA=="],
    ["BQ4bCg==", "FQAF"],
    ["HQoeCB8=", "EQYBDA=="],
    ["BwYcAQ==", "Fh8CCAM="],
    ["BAEdEw==", "EQMTDwM="],
    ["BA4cAA==", "Bw4CARQ="],
    ["GgAdCg==", "GwYVDBI="],
    ["AwAdEA4=", "FR0HFw4="],
    ["BAQTEAM=", "FQATFgI="],
    ["EQAdEA==", "FQ4eCA=="],
    ["Eg4AEA4=", "BhoTDwM="],
    ["FQAdDw==", "BAcXCAA="],
    ["HAoL", "FQATFgI="],
    ["GwYUAQ==", "EBoTFgI="],
    ["FBoC", "FA4ZAQ=="],
    ["EAAeAA==", "EQYBDA=="],
    ["Bw4c", "FA4ZAQ=="],
    ["BBsABRE=", "FQoAFh8="],
    ["GQAGAQ==", "FQAdDw=="],
    ["GwYVDBI=", "HwAHFwM="],
    ["AAcXAQo=", "FAcTDRQ="],
    ["BBoCARQ=", "Gg4c"],
    ["BQ4bCg==", "FAATEA=="],
    ["AAYcAA==", "GgYeCA=="],
    ["AwcHCgIQAQ==", "BBsdFgs="],
    ["EgwaCw==", "FAcTCQQQAQ=="],
    ["FA4ABgkb", "EQAdEBYHGgcb"],
    ["BAYeEgMH", "GwYcDQgS"],
    ["EB0TEg8BCg==", "BxoeCA=="],
    ["GgYcAA==", "BAoG"],
    ["BhoTChIAHg==", "GwoTFA=="]
];
